### ISSUE TITLE
Dependencies for the MAVLINK library

### ISSUE THREAD

**Issue by ukhov79** [okalachev/flix#1]
It would be cool to add dependencies for the MAVLINK library:
https://github.com/mavlink/c_library_v2

**Comment by okalachev** [comment]
You're absolutely correct, now this dependency handling totally missing. I was thinking about how I would handle it, using github submodules or download in `Makefile`, and now I'm planning to add downloading with the `Makefile` (I don't like submodules).

**Comment by okalachev** [comment]
If you want to build with Wi-Fi and MAVLink, you may download MAVLink library manually and put it to the `flix` directory.

**Comment by ukhov79** [comment]
Yes, I did. everything worked perfectly. Thanks!
However, my Arduino IDE sometimes refuses to upload code to the board and I have to restart IDE.
Have you thought about using platformio-ide and vs code? It seems easier to manage dependencies and libraries there.

**Comment by okalachev** [comment]
I guess the recommended way to edit this code for experienced developers is using VSCode and console for building and uploading. I have VSCode config files that make IntelliSense work with the Arduino code and the simulation code, I just have not committed them yet (they are not portable enough).

**Comment by okalachev** [comment]
@ukhov79, I decided to solve this in a radical way, without using submodules or Makefile downloads. I created an [Arduino library](https://github.com/okalachev/mavlink-arduino) that allows to install MAVLink in an easy Arduino way, and utilized it in this project.

So if you can check if it works, that would be helpful.

**Comment by ukhov79** [comment]
Great solution! It works!
