### ISSUE TITLE
make simulator. No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by lejkaxdd** [okalachev/flix#4]
Trying to do make simulator and got error

make -C gazebo/build
make[1]: Entering directory '/home/uganda/Desktop/flix/gazebo/build'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/uganda/Desktop/flix/gazebo/build'
make: *** [Makefile:28: build_simulator] Error 2

**Comment by okalachev** [comment]
Hi! You should `cd` into the cloned flix directory and do `make simulator`. Did you do that or some other command?

Also, there are instructions on building and running the sim: https://github.com/okalachev/flix/blob/master/docs/build.md#simulation.

**Comment by lejkaxdd** [comment]
Hi!

I solved the problem, I had to install MAVLink, and correctly connect the library in the mavlink.ino file
https://mavlink.io/en/mavgen_c/

**Comment by okalachev** [comment]
Well, actually MAVLink should be [installed](https://github.com/okalachev/flix/blob/fff7262d1bb5c3657cab2ba480ca9db5483a8ac4/Makefile#L19) when you did `make simulator` via Arduino library (https://github.com/okalachev/mavlink-arduino), but if it works, then ok.
