### ISSUE TITLE
Small value with calibrateAccel

### ISSUE THREAD

**Issue by Igor743646** [okalachev/flix#5]
0.3 second is to small for wating: 
[    Serial.println("Cal accel: upside down"); delay(300);](https://github.com/okalachev/flix/blob/44ed3cf42c74d6015a9d6399044edf75b559b195/flix/imu.ino#L69)

**Comment by okalachev** [comment]
Hi, it's an old version of the code. In the current version it [waits until enter is pressed](https://github.com/okalachev/flix/blob/fff7262d1bb5c3657cab2ba480ca9db5483a8ac4/flix/imu.ino#L70C40-L70C68).

**Comment by ukhov79** [comment]
Could you update run-sim branch? I think it is there.

**Comment by okalachev** [comment]
@ukhov79, hi you should not use run-sim branch, this branch is only for adding a feature of running the sim in CI (for testing). There is nothing useful for users in this branch.
